### ISSUE TITLE
rake assets:precompile or db:setup will try to connection to the database, but, there is no db.

### ISSUE THREAD

**Issue by huobazi** [jrochkind/attr_json#41]
when database is not setup before, or  build a docker image or  deploy to a new server fist time 

``` ActiveRecord::NoDatabaseError ``` and ``` PG::ConnectionBad: ```  will got

the error stack trace to

https://github.com/jrochkind/attr_json/blob/544f8e9388ec2ffdf261fce4daa3bb403c2bd535/lib/attr_json/attribute_definition.rb#L43

when ``` bundle exe  rake assets:precompile ```, i  got
```
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
...
```
when ``` bundle exec rake db:setup ``` , i got

```bash
Caused by:
app_1            | PG::ConnectionBad: FATAL:  database "xxxxxx" does not exist
app_1            | /usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
app_1            | /usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `new'
app_1            | /usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:90:in `connection'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/type.rb:52:in `current_adapter_name'
app_1            | /usr/local/bundle/gems/activerecord-5.2.2/lib/active_record/type.rb:41:in `lookup'
app_1            | /usr/local/bundle/gems/attr_json-0.4.0/lib/attr_json/attribute_definition.rb:43:in `initialize'
app_1            | /usr/local/bundle/gems/attr_json-0.4.0/lib/attr_json/model.rb:112:in `new'
app_1            | /usr/local/bundle/gems/attr_json-0.4.0/lib/attr_json/model.rb:112:in `attr_json'
```

**Comment by jrochkind** [comment]
Oh, that's too bad. Thanks for the good error report. 

I used to use `ActiveModel::Type.lookup`, but the ActiveModel date types don't cast timezones properly, so I switched to `ActiveRecord::Type.lookup`. 

That is annoying that apparently you can't do that without a database. Hmm. I'll try to look into it more. 

Is precompiling assets before you have a database setup something you normally do? And it normally works, when you aren't using attr_json?  

I'm curious why the precompile assets was trying to load the model at all. Ah, are you in Rails `production` mode, so it's eager loading all files?

**Comment by jrochkind** [comment]
Oh, but the `bundle exec rake db:setup` doesn't work for you either. That is definitely not ordinary. Hmm, very odd. Can you paste (maybe into a gist.github.com) the entire stack trace, as well as your entire model class source code (where you define the attr_json's)?

**Comment by jrochkind** [comment]
Hmm, I just made a simple "hello world" kind of app with Rails 5.2.2 and attr_json. 

I was able to `bundle exec rake assets:precompile` without a database being created yet, and also was able to `bundle exec rake db:setup` no problem.  Also tried with `RAILS_ENV=production`, still no problem. 

So it's something specific to your app. If it's something in attr_json, I do want to figure out and see if it can be improved. 

But just to rule it out, I wonder if it's not actually related to attr_json at all. I am curious, if you can try, if you remove all the `attr_json` calls from your model code, and try to `assets:precompile` or `db:setup`, I wonder if you still get the error anyway?

**Comment by huobazi** [comment]
thanks for your awesome gem, and thanks for your response about this issue

i tried many ways to reproduce the error in simple hello world app, then the error is reproduce, i push the repo to  https://github.com/huobazi/hello

but,  I'm very confused. because any two or one of the three gems ([devise](https://github.com/plataformatec/devise) [action-store](https://github.com/rails-engine/action-store) [attr-json](https://github.com/jrochkind/attr_json)）  will work fine, but the three will make error together.

the full trace is https://gist.github.com/huobazi/1a7b9742aa31741ef95d5d1e83a64890

### STEP

make a simple app with rails 5.2.2.2.  
then  add attr_json, 
it looks like very fine when ```assets:precompile``` and ```db:setup```
then  add the gem [devise](https://github.com/plataformatec/devise) 
it also looks like fine.
then  add the gem [action-store](https://github.com/rails-engine/action-store)
🐛 error is reproduce...

**Comment by jrochkind** [comment]
Nice job making a reproduction, thanks. That is disconcerting. I'll try to find some time to analyze it and try to understand what's going on.

**Comment by jrochkind** [comment]
OK, this is a weird and challenging one. 

Indeed, the `attr_json :my_string, :string` can't be evaluated without a db existing. We'll get to more about why that is later. 

In ordinary Rails, it is _not_ evaluated when you run `rake db:setup` -- even in production mode with rails eager-loading, the db:setup somehow happens without/before doing a load of all your model files. I'm not sure why it _doesn't_ load the model before trying to execute the task, even with eager loading turned on, but we'll just accept that and move on.  

The combination of devise and action-store results in your model file being loaded earlier in `db:setup` (and other rake tasks), and causing an exception. 

1. Rails does load it's routing file early, even when you are doing rake tasks like db:setup
2. The `devise_for` call in the routing file, with `to: :user`, triggers a load of your `User` class. The `User` class alone could load fine in your demo app, because it doesn't use `attr_json`. But. 
3 Since your `User` class has `action_store :favorite, :item`, it triggers a load of the `Item` class. 
4. Which does have attr_json, which then tries to define an attr_json property with type `:string`, which triggers the exception when the database isn't there. 

I suspect this would also happen without `action_store`, if your `User` class had an _association_ to a class with attr_json (but I'm not sure) -- and definitely if your user class had `attr_json` itself. 

So this is probably `attr_json`s fault. Even though a typical out of the box Rails app can do rake tasks without loading models, it probably ought to be possible to load the model files even without the database created yet, because without `attr_json` it is. 

### So why does `attr_json` make it raise?  

When you say `attr_json :some_string, :string`, attr_json tries look up that `:string` argument with `ActiveRecord::Type.lookup(type)`. 

That implementation [by default calls it's own private current_adapter_name](https://github.com/rails/rails/blob/ce48b5a366482d4b4c4c053e1e39e79d71987197/activerecord/lib/active_record/type.rb#L41) method, in case there are special adapter-specific type overrides. current_adapter_name [tries to establish a db connection, just to get the adapter name](https://github.com/rails/rails/blob/ce48b5a366482d4b4c4c053e1e39e79d71987197/activerecord/lib/active_record/type.rb#L52).  :( 

Why are we using `ActiveRecord::Type.lookup` instead of `ActiveModel::Type.lookup`?  Because ActiveModel::Type date and time types don't work with multi-param assignment, like ActiveRecord ones are, leading to confusing behavior with `attr_json` `:date` and `:datetime` types where you can't use the Rails default select menu inputs. [So we switched](https://github.com/jrochkind/attr_json/commit/d6b3641b1c7d6fa561ffa8e243d67100e34bb3a7)

Phew, what a bunch of confusing combination of circumstances. 

### What should we do? What is the thing that is actually wrong?

* A) Arguably it is a bug that ActiveModel::Type's don't work with multi-param date assignments. Should we file this bug with Rails and/or a PR?  Maybe, but my experience with Rails is it might just sit there without attention, or Rails devs may think it is appropriate the way it is. 

* B) Should `ActiveRecord::Type#current_adapter_name` be able to get the adapter name without actually making a connection?  Probably. I think it could by doing `ActiveRecord::Base.connection_config[:adapter]` instead of `ActiveRecord::Base.connection.adapter_name.downcase.to_sym`. I may file that PR, but it may just sit there, or there may be reasons my solution doesn't work. (I have verified that this would fix our problem though). 

* C) Should `attr_json` use `ActiveModel::Type` instead of `ActiveRecord::Type`? That would mean either breaking multi-param date assignment under default use, or doing something special to normally use `ActiveModel::Type`, but use a custom type of some kind for `:date` and `:datetime`. This seems convoluted either way. 

* D) Can `attr_json` _not_ load the types as soon as the class loads, wait until there is actually a database connection to use them?  It is at least theoretically possible. We [already use attributes_to_define_after_schema_loads](https://github.com/jrochkind/attr_json/blob/master/lib/attr_json/record.rb#L112) to try trigger code only after connection is loaded in another case. But I'm not sure if that is really public Rails API, and it just seems like an over-complicated solution, risking further weird interactions. 

* E) Can `attr_json` use `ActiveRecord::Type` under current activerecord code, without triggering a connection call?  It turns out, yes, if we do: `ActiveRecord::Type.lookup(whatever, adapter: nil)`. This will mean it will never use any database-specific type code... which is actually maybe _preferable_. 

### What will I do

I think I will implement "E".  The hard part is making a test that proves model classes can be loaded without a db connection. I think I can do that though. 

I think I will make a PR to Rails for "B", and file an issue for "A". Although I'm not holding my breath for action to be taken on either, and it wouldn't be in a Rails release probably until 6 anyway. 

I may sit on this a while to think about it first. This was a lot of text, sorry! @onomated, you're my code buddy here who knows something about this code other than me, if you have any time/interest in reading this over and giving feedback, I'd appreciate it!

@huobazi If you want a temporary work-around, and I know this is ugly and not great, you could do either of these, on every single `attr_json` call:

    attr_json :my_string, ActiveModel::Type.lookup(:string)
    attr_json :my_string, ActiveRecord::Type.lookup(:string, adapter: nil)

(I have verified these will work)

Phew, that was a lot! Thanks for the report and your work to make a good reproduction!

**Comment by jrochkind** [comment]
On "A", ActiveModel::Type::Date and DateTime already have code that _appears_ to look like it's supposed to handle multi-param assignment. I will have to do more investigation on what wasn't working to be able to file a Rails GH issue.

**Comment by jrochkind** [comment]
(B) is hard to PR to rails too. :(  `ActiveRecord::Base.connection_config[:adapter]` doesn't always return the same string as `ActiveRecord::Base.connection.adapter_name.downcase.to_sym`. For instance `sqlite` vs `sqlite3`. May not have time to figure out how to PR or GH Issue to Rails in a productive way, might just keep working around locally.

**Comment by jrochkind** [comment]
@huobazi I went ahead and merged to master. Let me know if it resolves for you?

I think I just ran into a similar problem too, so was glad I had already investigated in response to this issue! Thanks for trying out attr_json and reporting your problems!
