### ISSUE TITLE
currently failing on rails edge (6.1)

### ISSUE THREAD

**Issue by jrochkind** [jrochkind/attr_json#92]
Looks like it may be particular to the new "single model serialized to json field" feature we just added in #89... they may have removed the feature we are using for this from Rails 6.1?? DOH!

Needs more investigation. 

```
  1) AttrJson::Model with ActiveRecord serialize to one column will cast from hash
     Failure/Error: record_instance.other_attributes = embedded_model_attributes
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./spec/single_serialized_model_attribute_spec.rb:58:in `block (2 levels) in <top (required)>'

  2) AttrJson::Model with ActiveRecord serialize to one column can assign and save from model class
     Failure/Error: record_instance.other_attributes = model_value
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./spec/single_serialized_model_attribute_spec.rb:44:in `block (2 levels) in <top (required)>'
 
 3) AttrJson::Model with ActiveRecord serialize to one column with existing value can set to nil
     Failure/Error: let(:record_instance) { record_class.new(other_attributes: embedded_model_attributes)}
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # ./spec/single_serialized_model_attribute_spec.rb:72:in `block (3 levels) in <top (required)>'
     # ./spec/single_serialized_model_attribute_spec.rb:75:in `block (3 levels) in <top (required)>'
```

**Comment by jrochkind** [comment]
This may actually be a bug in rails itself, breaking `serialization` with a custom coder or custom type. 

Serialization tries to:

```
        if coder.respond_to?(:assert_valid_value)
          coder.assert_valid_value(value, action: "serialize")
        end
```

But then default `assert_valid_value` (which is no-op) now takes a single argument instead of a splat, so it calls it and raises....

Have to figure out how to reproduce with simple example to report to rails.... It might be reproducible with any custom Serialize on a jsonb column. 

Why did the signature of default `assert_valid_value` change?

**Comment by jrochkind** [comment]
> Why did the signature of default assert_valid_value change?

Looks like it was done in an unrelated commit, weird. https://github.com/rails/rails/commit/d29d4598972e85df7ee42f5aa969b51d1b14d615

**Comment by jrochkind** [comment]
Problem was that a Serialization "Coder" has a `assert_valid_value` with a different signature than an ActiveModel::Type. Trying to use the same object for both wound up colliding, we've separated them in #93 , better OO design anyway.
